
name: Deploy to Gihub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: allthingsembedded.com

  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify -D --baseURL https://allthingsembedded.com/staging-web

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          publish_dir: ./public
          external_repository: allthingsembedded/staging-web
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
